version: "3.8"
services:
  boombot:
    env_file: 
        - boombot.env
    # image: boombot-local-dev:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: boombot
    restart: on-failure
    links:
      - yt-api
    depends_on:
      - yt-api
  
  yt-api:
    container_name: yt-api
    image: mwader/ydls
    restart: on-failure
    ports: 
      - "8080:8080"