version: "3.8"
services:
  boombot:
    env_file: 
        - boombot.env
    image: aplombomb/boombot
    container_name: boombot
    restart: on-failure
    links:
      - yt-api
    depends_on:
      - yt-api
      - db
    deploy:
      resources:
        limits:
          cpus: '0.50'
        reservations:
          cpus: '0.25'
  
  yt-api:
    container_name: yt-api
    image: mwader/ydls
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '4'
        reservations:
          cpus: '3'

  db:
    env_file: 
      - db.env
    container_name: pgDB
    image: postgres
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.10'
        reservations:
          cpus: '0.25'

  dbUI:
    image: adminer
    restart: always
    ports: 
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.10'
        reservations:
          cpus: '0.25'