version: "3.8"
services:
  boombot:
    env_file: 
        - boombot.env
    image: aplombomb/boombot
    container_name: boombot
    restart: on-failure
    links:
      - yt-api
    depends_on:
      - yt-api
      - db
  
  yt-api:
    container_name: yt-api
    image: mwader/ydls
    restart: on-failure
    ports: 
      - "8080:8080"

  db:
    env_file: 
      - db.env
    container_name: pgDB
    image: postgres
    restart: on-failure      